name: rivgraph
channels:  
  - conda-forge
dependencies:
  - python=3
  - geopandas
  - scikit-image
  - opencv
  - networkx<2.7 # necessary for correct numpy ops
  - shapely
  - matplotlib
  - fastdtw
  - loguru
