# This workflow installs and tests the RivGraph package

name: build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'  # run workflow at 12AM on first day of every month


jobs:
  ubunutu-build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          activate-environment: rivgraph
          environment-file: conda-linux-64.lock
      - name: install RivGraph + dependencies, then unit test
        run: |
          conda env list
          pip install pytest pytest-timeout pytest-cov coveralls coverage
          python setup.py install
          coverage run -m pytest --cov-config=.coveragerc --cov=rivgraph/
          conda list

  windows-build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          channels: conda-forge
          activate-environment: rivgraph
          environment-file: conda-win-64.lock
      - name: install RivGraph + dependencies, then unit test
        run: |          
          conda env list
          pip install pytest pytest-timeout pytest-cov coveralls
          pip install --upgrade -e .
          python -m pytest --cov-config=.coveragerc --cov=rivgraph/
          conda list
